### PR TITLE
Add types to the 'mget' API

### PR DESCRIPTION
**Pull request by sethmlarson**
Wasn't sure about `MultiGetSourceFilter` but `mget` seems to use slightly different attributes for it's source filtering unfortunately?

### CODE REVIEW

**Comment by delvedor** [comment]
Can you rebase on master?

**Comment by delvedor** [comment]
Please also take a look at https://github.com/elastic/elastic-client-generator/issues/71 :)

**Comment by sethmlarson** [comment]
Getting some errors locally I'm not sure about, just pushed to see if CI agrees:

```
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> elasticsearch-client-specification@0.0.1 prepare /home/sethmlarson/elastic-client-generator
> npm run compile:specs && npm run copy:specs


> elasticsearch-client-specification@0.0.1 compile:specs /home/sethmlarson/elastic-client-generator
> npm run compile:specs --prefix specification


> elasticsearch-client-specification@0.0.1 compile:specs /home/sethmlarson/elastic-client-generator/specification
> tsc

src/format.ts:25:43 - error TS2532: Object is possibly 'undefined'.

25 const response = specification.typeLookup[api.typeMapping.response]
                                             ~~~

src/format.ts:30:1 - error TS2578: Unused '@ts-expect-error' directive.

30 // @ts-expect-error
   ~~~~~~~~~~~~~~~~~~~

src/format.ts:37:1 - error TS2578: Unused '@ts-expect-error' directive.

37 // @ts-expect-error
   ~~~~~~~~~~~~~~~~~~~


Found 3 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! elasticsearch-client-specification@0.0.1 compile:specs: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the elasticsearch-client-specification@0.0.1 compile:specs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sethmlarson/.npm/_logs/2021-01-28T22_07_26_738Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! elasticsearch-client-specification@0.0.1 compile:specs: `npm run compile:specs --prefix specification`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the elasticsearch-client-specification@0.0.1 compile:specs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sethmlarson/.npm/_logs/2021-01-28T22_07_26_773Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! elasticsearch-client-specification@0.0.1 prepare: `npm run compile:specs && npm run copy:specs`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the elasticsearch-client-specification@0.0.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sethmlarson/.npm/_logs/2021-01-28T22_07_26_827Z-debug.log
```

**Review by delvedor — APPROVED** [review]
LGTM

**Pull request merged**
