### PR TITLE
Fix indices.flush_synced response

### PR DESCRIPTION
**Pull request by stevejgordon**

### CODE REVIEW

**Review by philkra — APPROVED** [review]
LGTM

**Review by delvedor — COMMENTED** [review]
The fix looks ok! I want to do a double check on `DictionaryResponseBase`.
Holding the merge for now :)

**Comment by stevejgordon** [comment]
@delvedor Yeah I basically followed the approach we use in NEST to produce that type, but if it needs tweaking, happy to do so :-)

**Review by delvedor — APPROVED** [review]
LGTM

**Pull request merged**
