### PR TITLE
Reorg Watcher

### PR DESCRIPTION
**Pull request by philkra**
ref: #409

### CODE REVIEW

**Review by delvedor — COMMENTED** [review]
I would move most of the nested definitions that are not requests or responses inside `watcher/_types`.

**Review by delvedor — DISMISSED** [review]
LGTM once the conflicts are resolved

**Comment by philkra** [comment]
@delvedor - conflicts resolved

**Comment by philkra** [comment]
conflicts resolved the 2nd 😄

**Review by delvedor — APPROVED** [review]

**Pull request merged**
