### PR TITLE
Snapshot Create Response

### PR DESCRIPTION
**Pull request by stevejgordon**
Fix response type to resolve failures. I reviewed the Java code to refine a few other fields which were missing/not marked as optional.

### CODE REVIEW

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by delvedor** [comment]
Can you rebase on master?

**Comment by stevejgordon** [comment]
@delvedor Done locally but due to a issue in types.cs I'm unable to validate it and push. Opening an issue for that as discussed.

**Comment by stevejgordon** [comment]
@delvedor It's rebased and I ran the code style fixes as well. Happy for me to merge this now?

**Review by delvedor — APPROVED** [review]
LGTM

**Pull request merged**
