### PR TITLE
Add types for the 'indices.clone' API

### PR DESCRIPTION
**Pull request by sethmlarson**

### CODE REVIEW

**Review by philkra — DISMISSED** [review]
LGTM

**Review by delvedor — CHANGES_REQUESTED** [review]
Changes LGTM, can you regenerate the output? :)

**Comment by Mpdreamz** [comment]
Love seeing `Check output freshness / build (pull_request)` though :1st_place_medal: @delvedor :cat:

**Comment by sethmlarson** [comment]
@delvedor Regenerated the spec ready for another review

**Review by delvedor — APPROVED** [review]
LGTM

**Pull request merged**
